### ISSUE TITLE
Could not build the code

### ISSUE THREAD

**Issue by jczhang07** [exafmm/exafmm#1]
I cloned the master but could not build the code.  After successful ./configure,  I typed make and met
make[2]: *** No rule to make target `fmm.cxx', needed by `laplace-fmm.o'.  Stop.

BTW,  I searched ExaFMM on Internet.  It looks Dr. Rio Yokota said the code "is written in C++/CUDA/OpenMP/MPI."  But I could not find any MPI calls in the source.

**Comment by rioyokota** [comment]
ExaFMM is going through a major update. The code you are looking for is under exafmm/exafmm-alpha.
