### ISSUE TITLE
Update autoconf

### ISSUE THREAD

**Issue by rioyokota** [exafmm/exafmm#2]
1. Update autoconf so it work for all directories; 2d, 2dp, 3d, 3dp

2. Use ax_ext.m4 instead of having so many entries for SIMD detection in configure.ac

**Comment by rioyokota** [comment]
At the moment it is adding sse, avx, and avx512 flags all at the same time if they are available and is causing warnings. Please fix this so that it only selects the last option.

**Comment by tingyu66** [comment]
resolved by ac20871
