### ISSUE TITLE
vector resize in  can lead to new memory adress

### ISSUE THREAD

**Issue by pizzooid** [exafmm/exafmm#24]
[source](https://github.com/exafmm/exafmm/blob/1a8c403a4178e7eff200378be91c0f8cfed0055c/3d/build_tree.h#L66-L81)
```
    cells.resize(cells.size()+cell->NCHILD);
    Cell * child = &cells.back() - cell->NCHILD + 1;
    cell->CHILD = child;
    int c = 0;
    for (int i=0; i<8; i++) {
      Xchild = X;
      real_t r = R / (1 << (level + 1));
      for (int d=0; d<3; d++) {
        Xchild[d] += r * (((i & 1 << d) >> d) * 2 - 1);
      }
      if (size[i]) {
        **buildCells**(buffer, bodies, offsets[i], offsets[i] + size[i],
                   &child[c], cells, Xchild, R, level+1, !direction);
        c++;
      }
    }
```
I think: If buildCells calls itself then resizes it could use a different memory address, causing &child[c] of the calling function i.e. cell of the called function to become a dangling pointer.

This can happen if the number of cells exceeds the number of bodies.

**Comment by rioyokota** [comment]
That won't happen as long as reserve() is done with a large enough size. The alternative would be to calculate the size with a fast traversal for a minimal tree structure and then use that to allocate the larger data structure for cells. I chose the former because it is simpler and reserve() is fast.

**Comment by pizzooid** [comment]
ok, but an error should be thrown if the reserved size is too small

**Comment by rioyokota** [comment]
Ok. Theoretically, the number of nodes in a tree cannot exceed twice the number of leafs, and the number of leafs cannot exceed the number of bodies. So setting reserve to 2*bodies.size() should be safe.
