### ISSUE TITLE
Invalid array assignment with non-constant size

### ISSUE THREAD

**Issue by allo-** [exafmm/exafmm#29]
In kernel.h, the array definitions like ``complex_t Ynm[P*P]`` do not work, because P is no constant.
I think this should probably be changed like this:

    diff --git a/3d/kernel.h b/3d/kernel.h
    index 7c0c153..ae518b1 100644
    --- a/3d/kernel.h
    +++ b/3d/kernel.h
    @@ -130,7 +130,8 @@ namespace exafmm {
            }
    
            void P2M(Cell * C) {
    -               complex_t Ynm[P*P], YnmTheta[P*P];
    +               complex_t * Ynm = (complex_t*)malloc(sizeof(complex_t)*P*P);
    +               complex_t * YnmTheta = (complex_t*)malloc(sizeof(complex_t)*P*P);
                    for(Body * B = C->body; B!=C->body+C->numBodies; B++) {
                            vec3 dX = B->X - C->X;
                            real_t rho, alpha, beta;
    @@ -144,10 +145,13 @@ namespace exafmm {
                                    }
                            }
                    }
    +               free(Ynm);
    +               free(YnmTheta);
            }

(Change the other 4 instances in the same way)

**Comment by rioyokota** [comment]
That would have a huge performance hit because the arrays will be allocated in heap. I also prefer to use STL vectors over malloc or new. This should be done outside the function and Ynm should be declared as static global variables in that case.

**Comment by allo-** [comment]
Thank you, i will try it. Can you give me some hint what compiler feature allows your syntax?
I would have thought such array declarations need to be static, but I am not the expert at low level C code. Maybe I get MSVC to use it in a similar way.

**Comment by rioyokota** [comment]
exaFMM has been tested to work on Linux OS like Ubuntu, CentOS, Suse, Fedora, etc. with GNU, Intel, PGI, and Cray compilers. I don't know anyone who runs it on non-Linux environments. It takes a lot of effort to support non-Linux users because the environment is so old (like OpenMP 2.0). The code turns into macro hell, and I don't have the human resources to support such software, as an academic.

**Comment by allo-** [comment]
I know the problems ... I am developing here academic code as well, but currently I have to develop using windows for and every second library needs patching before it works.

I'll try if I get it to work without too many changes and if the diff isn't too ugly I may put it in a fork and you can have a look how much of it you like to merge it or not.

**Comment by rioyokota** [comment]
If you are willing to do this, then it would be very useful to us. I am not against windows or anything. I just haven't had the need to support it until now.

**Comment by allo-** [comment]
Here the compile fixes for ``exafmm.h``. 
Porting ``fmm.cxx`` would require choosing a working getopt implementation for windows or implementing ``args.h`` with another option parsing library for windows.
https://github.com/allo-/exafmm/tree/msvc_fixes

**Comment by allo-** [comment]
For the record: The feature is called Variable length assignment (VLA), supported by recent GCC and Clang but non-standard. MSVC could probably use alloca() to assign dynamic memory on the stack, which is also non-standard and not guaranteed to be implemented by a compiler.
I currently stay with the fix linked above.
