### ISSUE TITLE
cells.resize() invalidates the pointer to the current cell

### ISSUE THREAD

**Issue by allo-** [exafmm/exafmm#30]
The resize Operation at https://github.com/exafmm/exafmm/blob/4a884e63af87f736a2545588b1137461dda840eb/3d/build_tree.h#L66
can change the total size of the cells vector, which invalidates all references to elements from the vector, as created at
https://github.com/exafmm/exafmm/blob/4a884e63af87f736a2545588b1137461dda840eb/3d/build_tree.h#L67

I will look into it tomorrow, but possibly the easiest way to fix it is to replace the ``Cell * cell`` parameter by ``size_t cell_index`` and use ``cells[cell_index]`` everywhere, as it is probably hard to tell how much elements to reserve before the recursion.

**Comment by rioyokota** [comment]
The reserve() function is used outside of this function so that reallocation does not occur. I have experimented with many different designs and this seems to be the cleanest implementation for a dynamic allocation when the vector size is not known a priori.

**Comment by allo-** [comment]
I thought so, but access (just assigning it to a variable) to cell->numChilds just before works and just after the line it produces a segfault. I will debug it tomorrow.

**Comment by allo-** [comment]
I think I see the problem (I cannot test until tomorrow):

You reserve ``N`` cells
https://github.com/exafmm/exafmm/blob/4a884e63af87f736a2545588b1137461dda840eb/3d/build_tree.h#L90

And if I am not mistaken, you create ``O(N log N)`` cells in the tree. This works with a big enough ``NCRIT`` fine if ``N`` is not too big. I currently use ``NCRIT=1`` while integrating the library, so I hit the limit of the vector during resize.

**Comment by rioyokota** [comment]
exaFMM is not meant to be used for NCRIT=1. You may see other problems if you use NCRIT=1. By the way, a tree with 0(N) leafs still has order O(N) cells. This is because the number of cells decreases exponentially as you go up the tree. It's basically a geometric series. For an octree with NCRIT=1 you may have up to N*8/7 cells. For a binary tree you will have N*3/2. For an extremely non-uniform distribution the number might increase slightly more. In any case cells.reserve(2*bodies.size()) should be safe.

**Comment by rioyokota** [comment]
FMM achieves O(N) complexity only when the P2P kernel is balanced with the M2L kernel. Decreasing NCRIT increases the M2L kernel time. This balance is affected by the order of expansion P. The default value is set to achieve the optimal time.

**Comment by allo-** [comment]
Thank you.
Then the problem will solve itself with a higher value. I hope you don't mind me posting this when I find such a segfault. I try only to post things which are relevant to the lib project.

Or do you prefer, when I create a fork? I am not sure if you want to maintain it as open source or merely released it with an open source licence but maintain it in your institute.

**Comment by rioyokota** [comment]
Please post any problems you find here. I usually respond quickly. You can submit a pull request when your fork is stable.

**Comment by allo-** [comment]
Just as Feedback: It works with increased ``NCRIT`` and the library works fine in my program.

For the other things I opened issues and for the windows stuff I will create pull requests when I implemented the fixes in a nice way. And I need to look at the other folders, currently I am just working in the ``3d`` folder.
