### ISSUE TITLE
Evaluation at a point in space

### ISSUE THREAD

**Issue by allo-** [exafmm/exafmm#32]
Is there a function to evaluate the fields on a (neutral) position in space? I am not sure if I overlooked how to do it with the existing functions.

I want to build the tree one time and do the upward/horizontal/downward passes and then evaluate it on a lot of positions or if you want so uncharged bodies.
Currently I added the uncharged bodies to the set of all bodies for the first step, but for an iteration to trace particles through the field I need to evaluate it on new positions in each iteration while the positions of the charges are staying the same.

**Comment by rioyokota** [comment]
exaFMM is designed to handle different sources and targets. You need to create two sets of Bodies, one for the target and one for the source. Then call buildTree for each of them, upwardPass for just the sources, horizontalPass with target and source, downward for just the target, and you will have the field for all your target points. If the sources don't change you don't need the buildTree and upwardPass for the sources.

**Comment by allo-** [comment]
Thank you very much!
I think I may write some examples and/or documentation for such things when it works for me, possibly in a new repo.

**Comment by allo-** [comment]
Do I need to run upwardPass for both? 

I tried it with upwardPass only for the sources, but then ``Ci->L`` is not resized and ``Ci->L[jks] += L`` in ``M2L`` fails. I assume here, that Ci should be the targets, as ``P2P`` assigns the target values to ``Ci``.

When I swap them, I get an error at ``L += Cj->M[nms] * Cnm2 * Ynm2[jnkm];``, as ``Cj->M`` isn't resized then.

Or canI just run the resize to NTERM on the target cells before ``horizontalPass``?

**Comment by rioyokota** [comment]
This is a bug. L should be resized somewhere before horizontalPass. I will fix this

**Comment by allo-** [comment]
I currently resize ``L`` and ``M`` to ``NCRIT`` in my code between the exafmm calls and it works fine.

**Comment by rioyokota** [comment]
I have moved the resize of M and L to the build_tree when the cells are first created, which is how it should be.
