### ISSUE TITLE
Add tree.cxx and list.cxx unit tests

### ISSUE THREAD

**Issue by rioyokota** [exafmm/exafmm#5]
Add a unit test tree.cxx that creates N randomly distributed bodies with charge 1, builds the tree, and checks if the monopole of the root cell is N. This test should be compiled without any kernels.

Add a unit test list.cxx that creates N randomly distributed bodies with charge 1, builds the tree, creates the interaction lists, evaluates with fake P2P, P2M, M2M, M2L, L2L, L2P kernels that simply sum the charges to count how many bodies it is interacting with. The induced potential should be the number of bodies a given body interacts with and should be N.

**Comment by tingyu66** [comment]
commit 00151e4 added tree unit test, 
commit 060d1f8 added list unit test.
