### ISSUE TITLE
Extend buildbot tests to cover wide range of parameters

### ISSUE THREAD

**Issue by rioyokota** [exafmm/exafmm#6]
Make the buildbot tests run for different distribution, N, P, theta.
For the distribution use exafmm-alpha's cube, sphere, plummer
N={2, 10, 100, 1000, 10000, 100000, 1000000, 10000000}
P={4, 10, 20, 30, 40}
theta={.5, .4, .3, .2}

**Comment by tingyu66** [comment]
resolved by 8358005
